"""
Django settings for adverboard project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5_rh(n&yl4&mro(*tx9c2@@7j$$pud57=((89qnmcfii_hblbo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']  # добавили локальный адрес нашего сервера


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # installed by defaults. it is needed for django debug toolbar

    'django.contrib.sites',  # подключаем приложение Сайт
    'board',
    'sign',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # ... include the providers you want to enable:
    'allauth.socialaccount.providers.google',
    'django_extensions',  # include management commands, additional database fields, admin extensions and much more.
    'debug_toolbar',  # for django debug toolbar. This is the reason for not showing up the toolbar: in Windows,
    # edit the registry HKEY_CLASSES_ROOT\.js\Content Type from text/plain to text/javascript.
    # Then to clean cache files in Chrome settings.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',  # The Debug Toolbar is mostly implemented in a middleware.
]

ROOT_URLCONF = 'adverboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # by default, it is needed for django debug toolbar
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # в зависимости от версии Django может писать [BASE_DIR/'templates']
        'APP_DIRS': True,  # by default = True, it is needed for django debug toolbar
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.media',  # it is needed for MEDIA settings, I couldn't get the image on an template without the setting
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # it was installed by default, `allauth` needs this from django
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/accounts/login/'  # страница аутентификации
LOGIN_REDIRECT_URL = '/'  # страница, на которую перенаправляется пользователь после успешного входа на сайт

SITE_ID = 1

STATICFILES_DIRS = [
    BASE_DIR / "static"
]  # css files are not loading without the settings

WSGI_APPLICATION = 'adverboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # en-us

TIME_ZONE = 'Asia/Aqtau'  # UTC

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_EMAIL_REQUIRED = True  # поле email является обязательным
ACCOUNT_UNIQUE_EMAIL = True  # поле email является уникальным
ACCOUNT_USERNAME_REQUIRED = False  # username теперь необязательный
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # аутентификация будет происходить посредством электронной почты
ACCOUNT_EMAIL_VERIFICATION = 'none'  # указываем, что верификация почты отсутствует

INTERNAL_IPS = [  # The Debug Toolbar is shown only if your IP address is listed in Django’s INTERNAL_IPS setting
   '127.0.0.1',   # for local development, you must add "127.0.0.1" to INTERNAL_IPS.
]
