# Generated by Django 4.1.2 on 2022-10-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post',
            new_name='ad',
        ),
    ]
