# Generated by Django 4.1.2 on 2022-10-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_ad_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='poster',
            field=models.ImageField(blank=True, upload_to='ad_image/poster/%Y/%m/%d', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.ad'),
        ),
    ]
